### ISSUE TITLE
Add optional comments to record?

### ISSUE THREAD

**Issue by proofit404** [adamchainz/django-perf-rec#665]
### Description

```python
class AuthorPerformanceTests(TestCase):
    def test_special_method(self):
        with django_perf_rec.record() as rec:
            rec.info('api call 1')
            self.client.get('/authors')
            rec.info('api call 2')
            self.client.get('/users')
```
```yml
MyTests.test_home:
# api call 1
- cache|get: home_data.user_id.#
- db: 'SELECT ... FROM myapp_table WHERE (myapp_table.id = #)'
# api call 2
- db: 'SELECT ... FROM myapp_table WHERE (myapp_table.id = #)'
```
That way it would be easier to understand what actions lead to what calls.

What do you think?
